<?php
// module/Rss/view/rss/rss/delete.phtml:

$title = 'Delete rss';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($rss->title); ?>' by
    '<?php echo $this->escapeHtml($rss->name); ?>'?
</p>
<?php
$url = $this->url('rss', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $rss->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
