<?php
// module/Rss/view/rss/rss/index.phtml:

$title = 'Feeds';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('rss', array('action'=>'add'));?>">Add new rss</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $rss) : ?>
<tr>
    <td><?php echo $this->escapeHtml($rss->title);?></td>
    <td><?php echo $this->escapeHtml($rss->name);?></td>
    <td>
        <a href="<?php echo $this->url('rss',
            array('action'=>'edit', 'id' => $rss->id));?>">Edit</a>
        <a href="<?php echo $this->url('rss',
            array('action'=>'delete', 'id' => $rss->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partials/paginator.phtml', 'Rss'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'rss'
    )
);
?>
